In [66]:
import numpy as np
A = np.array( [ [2,1,1], [6,2,1], [-2, 2, 1] ])
b = np. array( [[1],[-1],[7]])
c = np.array((1,-1,7))
print(c)
print(b)
x = np.zeros(3)
B = np.array( [A[0], [0,0,0], [0,0,0]])
print(A)
A[0] = A[0]/A[0,0]
print(A)
A[1] = A[1] -A[0]*A[1,0]
print(A)
A[1] = A[1]/A[1,1]
A[2] = A[2] - A[0]*A[2,0]
A[2] = A[2] - A[1]*A[2,1]
print(A)
C = np.insert(A,3,c,axis=1)
print(C)
A[[0,1,2]] = A[[0,0,0]]
print(A)
print(A[0,0])
print(A[0][0])
print(A.shape[0])
print(x[0])

[ 1 -1  7]
[[ 1]
 [-1]
 [ 7]]
[[ 2  1  1]
 [ 6  2  1]
 [-2  2  1]]
[[ 1  0  0]
 [ 6  2  1]
 [-2  2  1]]
[[ 1  0  0]
 [ 0  2  1]
 [-2  2  1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[ 1  0  0  1]
 [ 0  1  0 -1]
 [ 0  0  1  7]]
[[1 0 0]
 [1 0 0]
 [1 0 0]]
1
1
3
0.0


In [81]:
def gaussian_elimation(A,b):
    A = A.astype(float)
    c = np.array((b[0,0],b[1,0],b[2,0]), dtype = float)
    A = np.insert(A,A.shape[1],c,1)
    print(c)
    print(A)
    for i in range (A.shape[0]):
        if A[i,0] != 0:
            if i == 0:
                break;
            else:
                A[[0,i]] = A[[i,0]]
                break;
        else:
            break;
    A[0] = A[0]/A[0,0]
    A[1] = A[1] - A[0]*A[1,0]
    A[1] = A[1]/A[1,1]
    A[2] = A[2] - A[0]*A[2,0]
    A[2] = A[2] - A[1]*A[2,1]
    A[2] = A[2]/A[2,2]
    print(A)
    A[1] = A[1] - A[2]*A[1,2]
    A[0] = A[0] - A[2]*A[0,2]
    A[0] = A[0] - A[1]*A[0,1]
    print(A)
    x = A[:,3]
    return x;

In [82]:
A = np.array( [ [2,1,1], [6,2,1], [-2, 2, 1] ])
b = np. array( [[1],[-1],[7]])
x = gaussian_elimation(A,b)
print(x)

[ 1. -1.  7.]
[[ 2.  1.  1.  1.]
 [ 6.  2.  1. -1.]
 [-2.  2.  1.  7.]]
[[ 1.   0.5  0.5  0.5]
 [-0.   1.   2.   4. ]
 [-0.  -0.   1.   1. ]]
[[ 1.  0.  0. -1.]
 [ 0.  1.  0.  2.]
 [-0. -0.  1.  1.]]
[-1.  2.  1.]
