In [1]:
#Name: Jiajin Liang
#Email: jil904@ucsd.edu
import numpy as np
dataset = np.load('pts.npy')
x = np.array([[0, 2], [1, 1], [2, 0]]).T
#print(dataset)
C=np.cov(dataset.T)
print("covariance matrix C=\n ",C)
U, S, VT = np.linalg.svd(C)
print("resultant matrices of SVD(C) = USVT are:")
print("U =\n%s" % (str)(U))
print("S =\n%s" % (str)(S))
print("VT =\n%s" % (str)(VT))
PC = U[:,0:1]
print("Principle Component is:\n %s" %(str)(PC))

covariance matrix C=
  [[  32.97692674 -258.01866014]
 [-258.01866014 2103.87358053]]
resultant matrices of SVD(C) = USVT are:
U =
[[-0.12180274  0.99255433]
 [ 0.99255433  0.12180274]]
S =
[2.13553671e+03 1.31379430e+00]
VT =
[[-0.12180274  0.99255433]
 [ 0.99255433  0.12180274]]
Principle Component is:
 [[-0.12180274]
 [ 0.99255433]]
